import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { Sidebar } from "@/components";
import { Nav } from "@/components/nav/Nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inter.className} h-screen overflow-hidden`}>
        <div className="flex">
          <Sidebar />
          <div className="flex-1 overflow-y-auto h-screen">
            <Nav />
            <div className="px-0 py-5 md:p-5">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
