import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { Sidebar } from "@/components";
import { Nav } from "@/components/nav/Nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${inter.className} flex flex-col gap-6 min-h-dvh dark:bg-gradient-to-br from-black via-black to-purple-950`}
      >
        {/* <Sidebar /> */}
        <main className="flex-1 mt-20">
          <Nav />
          <div className="flex justify-center w-full">
            <div className="xl:w-[1360px]">{children}</div>
          </div>
        </main>

        <div className="bg-red-600">
          <span>Footer</span>
        </div>
      </body>
    </html>
  );
}
