import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { Footer, Header, Nav, Sidebar } from "@/components";
import * as categoryAPI from "@/categories/helpers";
import { Breadcrumbs } from "@/components/breadcrumbs/Breadcrumbs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const getCategories = await categoryAPI.getCategories();

  const addSubCategories = getCategories.map(async (category) => {
    const subCategories = await categoryAPI.getSubCategoriesByParentId(
      +category.id
    );
    return {
      ...category,
      subCategories: subCategories ?? [],
    };
  });

  const resolvedSubCategories = await Promise.all(addSubCategories);

  return (
    <html lang="es">
      <body
        className={`${inter.className} flex flex-col gap-6 min-h-dvh dark:bg-gradient-to-br from-black via-black to-purple-950`}
      >
        <Header />
        {/* Versión desktop */}
        <Nav categories={resolvedSubCategories} />
        {/* Versión mobile */}
        <Sidebar categories={resolvedSubCategories} />

        <main className="flex-1 px-6 md:px-0">
          <div className="flex justify-center w-full">
            <div className="w-full mt-12 md:mt-0 md:w-10/12 2xl:w-full 2xl:max-w-[1360px]">
              <Breadcrumbs />
              {children}
            </div>
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
