CREATE TYPE "product_status" AS ENUM (
  'in_stock',
  'out_of_stock',
  'running_low'
);

CREATE TYPE "order_status" AS ENUM (
  'placed',
  'confirm',
  'processed',
  'complete'
);

CREATE TABLE "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) UNIQUE,
  "description" text,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp
);

CREATE TABLE "brand" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) UNIQUE,
  "description" text,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE,
  "name" varchar,
  "password" varchar,
  "description" text,
  "phone" varchar,
  "address" varchar,
  "role_user_id" int,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp
);

CREATE TABLE "product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) UNIQUE,
  "price" decimal(10,2),
  "status" product_status,
  "stock" int,
  "category_id" int,
  "brand_id" int,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp,
  "images" JSONB default '[]'
);

CREATE TABLE "order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" order_status,
  "user_id" int,
  "total" decimal(10,2),
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "order_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "product_id" int,
  "quantity" int
);

CREATE TABLE "role_user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text
);

CREATE TABLE "tecnogamer_log" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" int,
  "message" varchar,
  "method" varchar,
  "path" varchar,
  "status_code" int,
  "is_error" boolean,
  "request" text,
  "stack" text,
  "username" varchar,
  "headers" text,
  "level" varchar,
  "created_at" timestamp DEFAULT 'now()'
);

ALTER TABLE "user" ADD FOREIGN KEY ("role_user_id") REFERENCES "role_user" ("id");

ALTER TABLE "product" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");

ALTER TABLE "product" ADD FOREIGN KEY ("brand_id") REFERENCES "brand" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");




/****************** INSERTS ******************/

-- POPULATE ROLE_USER
INSERT INTO "role_user" ("name", "description") VALUES
('admin', 'Administrador del sistema con acceso completo'),
('customer', 'Cliente registrado que puede realizar compras'),
('support', 'Agente de soporte técnico'),
('inventory', 'Encargado de inventario');

-- POPULATE CATEGORY
INSERT INTO "category" ("name", "description") VALUES
	 ('Procesadores','Unidades centrales de procesamiento (CPU) para computadoras'),
	 ('Tarjetas de Video','Tarjetas gráficas (GPU) para procesamiento visual'),
	 ('Placas Madre','Placas base para conectar todos los componentes del sistema'),
	 ('Memoria RAM','Módulos de memoria de acceso aleatorio'),
	 ('Almacenamiento','Discos duros, SSD y otros dispositivos de almacenamiento'),
	 ('Periféricos','Teclados, ratones, auriculares y otros accesorios'),
	 ('Refrigeración','Sistemas de enfriamiento para componentes'),
	 ('Fuentes de Poder','Suministros de energía para computadoras'),
	 ('Monitores','Pantallas para visualización'),
	 ('Laptops','Computadoras portátiles'),
	 ('Gabinetes','Carcasa que contiene y protege los componentes internos de un PC');

-- POPULATE BRAND
INSERT INTO "brand" ("name", "description") VALUES
	 ('Intel','Fabricante líder de procesadores y chips'),
	 ('AMD','Fabricante de procesadores y tarjetas gráficas'),
	 ('NVIDIA','Especialista en tarjetas gráficas de alto rendimiento'),
	 ('ASUS','Fabricante de hardware y periféricos para PC'),
	 ('MSI','Fabricante de componentes para gaming'),
	 ('Corsair','Especialista en periféricos y componentes de PC'),
	 ('Kingston','Fabricante de dispositivos de almacenamiento y memoria'),
	 ('Western Digital','Especialista en soluciones de almacenamiento'),
	 ('Logitech','Fabricante de periféricos para computadoras'),
	 ('Gigabyte','Fabricante de hardware para PC'),
	 ('Cooler Master','Especialista en soluciones de refrigeración'),
	 ('EVGA','Fabricante de componentes de PC de alto rendimiento'),
	 ('HyperX','Marca de periféricos y componentes gaming'),
	 ('Samsung','Fabricante de dispositivos electrónicos y componentes'),
	 ('Acer','Fabricante de laptops y monitores'),
	 ('Cougar','Fabricante de gabinetes, periféricos, sillas y mesas gamer'),
	 ('NZXT','Fabricante de  gabinetes para PC, sistemas de refrigeración, fuentes de poder, placas base, iluminación RGB'),
	 ('LIAN LI','Fabricante de gabinetes'),
	 ('G.Skill','Fabricante de memorias ram de alto rendimiento');

-- POPULATE USER
INSERT INTO "user" ("email", "name", "password", "description", "phone", "address", "role_user_id") VALUES
('admin@tecnogamer.com', 'Administrador Principal', '$2a$10$hD7sSLy0ITHwTzL2hJz8y.XkJ1o1tD6rs.QYk5O7exgRTCnN1in3W', 'Administrador con acceso total al sistema', '+598 99123456', 'Oficina Central, Montevideo', 1),
('soporte@tecnogamer.com', 'Soporte Técnico', '$2a$10$Jx.p8LBwdx6NQoQPjLGkReYKlHJTvGzKzQFnlJoQ2dCM1qG5E0vPy', 'Agente de soporte para clientes', '+598 99654321', 'Oficina Central, Montevideo', 3),
('inventario@tecnogamer.com', 'Encargado de Stock', '$2a$10$RPSj6iK7RcHyVE9Rp.3AvOrXRmJVsiXCCvDJ0zTRKDfQxKLjQ.oHy', 'Responsable de administrar el inventario', '+598 99789012', 'Depósito Central, Montevideo', 4),
('juan.perez@gmail.com', 'Juan Pérez', '$2a$10$m9eCJ0LPQmcAz1zKYF0yJuR4YKYUSxZcOZJMdYZqWAYCOcj/KzCKK', 'Cliente frecuente', '+598 98123456', 'Av. Italia 1234, Montevideo', 2),
('maria.rodriguez@hotmail.com', 'María Rodríguez', '$2a$10$q5aK3PJ7TsO6KZsL9L9rCuEmXf1d.MLJt/B7nqzqKqJtQVj3k97xu', 'Cliente nuevo', '+598 96789012', 'Bulevar España 567, Montevideo', 2),
('carlos.gomez@yahoo.com', 'Carlos Gómez', '$2a$10$xZYtYGzO7QlRM0KR6qW8H.JWxbXQuWuJsBsP/7Y0v.nIA7W4qqQKe', 'Cliente gamer profesional', '+598 99345678', 'Luis Alberto de Herrera 890, Montevideo', 2),
('ana.martinez@gmail.com', 'Ana Martínez', '$2a$10$8kDfGMY5EL1CRf3HpzL9wOg8p1F.hKz5GYe7yU8V7NJmV9oZV1JlG', 'Cliente entusiasta de hardware', '+598 98567890', '18 de Julio 1234, Montevideo', 2),
('pedro.fernandez@outlook.com', 'Pedro Fernández', '$2a$10$4XA25fQ9J5OxLcgqvZ6FN.RWjnONGP.5TnWiuRCv6NmIBG9rONaDK', 'Cliente corporativo', '+598 95123456', 'Av. Brasil 567, Montevideo', 2);

-- POPULATE PRODUCT
INSERT INTO "product" ("name",price,status,stock,category_id,brand_id,created_at,updated_at,images) VALUES
	 ('Tarjeta de Video AMD Radeon RX 7900 XTX',999.99,'in_stock',15,2,2,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744255933/tecnogamer/tarjetas-video/alpxfops1nxcybdkuiox.png"]'),
	 ('Procesador Intel Core i5-11400',339990.00,'in_stock',42,1,1,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744255224/tecnogamer/procesadores/g777dc6kkfitodnsrowr.webp"]'),
	 ('Procesador Intel Core Ultra 7 265K',459990.00,'out_of_stock',37,1,1,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744255225/tecnogamer/procesadores/csxda48v7liedffvtefy.webp"]'),
	 ('Tarjeta de Video NVIDIA GeForce RTX 4070 Ti',649990.00,'in_stock',5,2,3,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744255930/tecnogamer/tarjetas-video/lszeznip1gnltpjqfola.webp"]'),
	 ('Procesador AMD Ryzen 9 9900X',599990.00,'in_stock',18,1,2,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744255224/tecnogamer/procesadores/tp8iv3xmjvc0v6ic3zco.png"]'),
	 ('Gabinete Cougar Gemini X',104990.00,'running_low',2,11,16,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744244909/tecnogamer/gabinetes/irxe3hyvpkn8itm9qdes.webp"]'),
	 ('Procesador AMD Ryzen 7 7800X3D',450000.00,'in_stock',22,1,2,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Gabinete Cougar MX360 RGB',89990.00,'in_stock',5,11,16,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744244909/tecnogamer/gabinetes/zckwwhznlx8wvyd6gyhf.webp"]'),
	 ('Tarjeta de Video NVIDIA RTX 4090',1599.99,'in_stock',10,2,3,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Placa Madre ASUS ROG Maximus Z790 Hero',599.99,'in_stock',12,3,4,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Placa Madre MSI MPG Z790 Carbon WiFi',479.99,'in_stock',18,3,5,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Placa Madre Gigabyte X670E Aorus Master',499.99,'running_low',8,3,10,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Memoria RAM Corsair Vengeance RGB 32GB DDR5',189.99,'in_stock',40,4,6,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Memoria RAM Kingston Fury Beast 32GB DDR5',179.99,'in_stock',35,4,7,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('SSD Samsung 990 Pro 2TB',249.99,'in_stock',30,5,14,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('HDD Western Digital Black 4TB',149.99,'in_stock',25,5,8,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('SSD Kingston KC3000 1TB',129.99,'in_stock',28,5,7,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Teclado Logitech G Pro X',149.99,'in_stock',50,6,9,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Mouse Logitech G Pro X Superlight',129.99,'in_stock',45,6,9,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Auriculares HyperX Cloud Alpha',99.99,'in_stock',38,6,13,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Refrigeración Líquida Corsair H150i Elite',189.99,'running_low',9,7,6,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Refrigeración por Aire Cooler Master Hyper 212',49.99,'in_stock',32,7,11,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Fuente de Poder EVGA SuperNOVA 850W 80+ Gold',139.99,'in_stock',20,8,12,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Fuente de Poder Corsair RM850x',149.99,'in_stock',18,8,6,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Monitor ASUS ROG Swift PG32UQX 32"',999.99,'running_low',7,9,4,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Monitor Samsung Odyssey G7 27"',649.99,'in_stock',15,9,14,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Laptop ASUS ROG Zephyrus G16',1899.99,'in_stock',12,10,4,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Laptop MSI Stealth 16',1799.99,'in_stock',10,10,5,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Laptop Acer Predator Helios 300',1499.99,'in_stock',14,10,15,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('NZXT H6 Flow - Black',149990.00,'in_stock',10,11,17,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744244909/tecnogamer/gabinetes/x5gq3fqzpauvmlikpjc5.webp"]'),
	 ('Lian Li Lancool 216 - Black RGB',79990.00,'in_stock',12,11,18,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744244910/tecnogamer/gabinetes/yfjf3opwnjixdysrf5kb.webp"]'),
	 ('Lian Li ODYSSEY X - Silver (TR-01A)',94990.00,'out_of_stock',0,11,18,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744244910/tecnogamer/gabinetes/stj9lmszsfzzuqkdezwu.webp"]'),
	 ('Procesador AMD Ryzen 9 7950X',550000.00,'in_stock',20,1,2,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Procesador Intel Core i9-13900K',600000.00,'in_stock',25,1,1,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Procesador Intel Core i7-13700K',410000.00,'in_stock',30,1,1,'2025-04-07 20:22:45.225393',NULL,'[]'),
	 ('Procesador AMD Ryzen 7 5800X',229900.00,'in_stock',10,1,2,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744255224/tecnogamer/procesadores/i6bex5stoopglksjzgs4.webp"]'),
	 ('Memoria RAM G.Skill Trident Z RGB 32GB',139990.00,'out_of_stock',0,4,19,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744255919/tecnogamer/memoria-ram/df3skun4lnsvvmsai27m.webp"]'),
	 ('Memoria RAM Kingston FURY Beast 16GB',89990.00,'in_stock',10,4,7,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744255920/tecnogamer/memoria-ram/qwp0dynvghk0loxlypig.webp"]'),
	 ('Tarjeta de Video NVIDIA GeForce RTX 4060 Ti',399990.00,'in_stock',25,2,3,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744255931/tecnogamer/tarjetas-video/ptck5mdfrmlzrl3ifph8.webp"]'),
	 ('Memoria RAM Corsair Vengeance RGB Pro 16GB',79990.00,'in_stock',23,4,6,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744255919/tecnogamer/memoria-ram/c1p9zfh2odcbyegx8nyj.webp"]'),
	 ('Tarjeta de Video NVIDIA RTX 4080 Super',1199.99,'running_low',5,2,3,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744255934/tecnogamer/tarjetas-video/n3bfkc8jmldntboalfsz.webp"]'),
	 ('Tarjeta de Video AMD Radeon RX 7800 XT',549990.00,'out_of_stock',0,2,2,'2025-04-07 20:22:45.225393',NULL,'["https://res.cloudinary.com/dq7ngio9s/image/upload/v1744255933/tecnogamer/tarjetas-video/xzw6yeuqsr8srxevy1qh.png"]');


-- POPULATE ORDER with related ORDER_ITEMS
-- Order 1 - Juan Pérez
INSERT INTO "order" ("status", "user_id", "total") VALUES
('complete', 4, 2039.97);

INSERT INTO "order_item" ("order_id", "product_id", "quantity") VALUES
(1, 3, 1),  -- Intel Core i7-13700K
(1, 9, 1),  -- MSI MPG Z790 Carbon WiFi
(1, 11, 2); -- Corsair Vengeance RGB 32GB DDR5 (2 unidades)

-- Order 2 - María Rodríguez
INSERT INTO "order" ("status", "user_id", "total") VALUES
('processed', 5, 1749.97);

INSERT INTO "order_item" ("order_id", "product_id", "quantity") VALUES
(2, 4, 1),  -- AMD Ryzen 7 7800X3D
(2, 6, 1),  -- AMD Radeon RX 7900 XTX
(2, 15, 1); -- Kingston KC3000 1TB

-- Order 3 - Carlos Gómez
INSERT INTO "order" ("status", "user_id", "total") VALUES
('confirm', 6, 1929.96);

INSERT INTO "order_item" ("order_id", "product_id", "quantity") VALUES
(3, 5, 1),  -- NVIDIA RTX 4090
(3, 16, 1), -- Teclado Logitech G Pro X
(3, 17, 1), -- Mouse Logitech G Pro X Superlight
(3, 18, 1); -- Auriculares HyperX Cloud Alpha

-- Order 4 - Ana Martínez
INSERT INTO "order" ("status", "user_id", "total") VALUES
('placed', 7, 1999.96);

INSERT INTO "order_item" ("order_id", "product_id", "quantity") VALUES
(4, 25, 1), -- Laptop ASUS ROG Zephyrus G16
(4, 18, 1); -- Auriculares HyperX Cloud Alpha

-- Order 5 - Juan Pérez (otro pedido)
INSERT INTO "order" ("status", "user_id", "total") VALUES
('complete', 4, 289.98);

INSERT INTO "order_item" ("order_id", "product_id", "quantity") VALUES
(5, 16, 1), -- Teclado Logitech G Pro X
(5, 17, 1); -- Mouse Logitech G Pro X Superlight

-- Insert some system logs
INSERT INTO "tecnogamer_log" ("code", "message", "method", "path", "status_code", "is_error", "request", "username", "headers", "level", "created_at") VALUES
(1001, 'Usuario iniciado sesión', 'POST', '/api/auth/login', 200, false, '{"email":"juan.perez@gmail.com"}', 'juan.perez@gmail.com', '{"user-agent":"Mozilla/5.0"}', 'info', NOW() - INTERVAL '2 days'),
(1002, 'Producto agregado al carrito', 'POST', '/api/cart', 201, false, '{"productId":3,"quantity":1}', 'juan.perez@gmail.com', '{"user-agent":"Mozilla/5.0"}', 'info', NOW() - INTERVAL '2 days'),
(1003, 'Orden creada', 'POST', '/api/orders', 201, false, '{"items":[{"productId":3,"quantity":1},{"productId":9,"quantity":1},{"productId":11,"quantity":2}]}', 'juan.perez@gmail.com', '{"user-agent":"Mozilla/5.0"}', 'info', NOW() - INTERVAL '2 days'),
(2001, 'Error de autenticación', 'POST', '/api/auth/login', 401, true, '{"email":"usuario.inexistente@gmail.com"}', 'anonymous', '{"user-agent":"Mozilla/5.0"}', 'error', NOW() - INTERVAL '1 day'),
(3001, 'Producto no encontrado', 'GET', '/api/products/999', 404, true, null, 'anonymous', '{"user-agent":"Mozilla/5.0"}', 'error', NOW() - INTERVAL '12 hours'),
(1004, 'Inventario actualizado', 'PUT', '/api/products/5', 200, false, '{"stock":10}', 'inventario@tecnogamer.com', '{"user-agent":"Mozilla/5.0"}', 'info', NOW() - INTERVAL '8 hours'),
(1005, 'Producto marcado como agotado', 'PATCH', '/api/products/7/status', 200, false, '{"status":"running_low"}', 'inventario@tecnogamer.com', '{"user-agent":"Mozilla/5.0"}', 'info', NOW() - INTERVAL '6 hours');